//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace ProcessVlive.WS_GetMedia {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetMediaSoap", Namespace="http://tempuri.org/")]
    public partial class GetMedia : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLinkMediaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLinkMediaByCateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetMedia() {
            this.Url = global::ProcessVlive.Properties.Settings.Default.ProcessVlive_WS_GetMedia_GetMedia;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLinkMediaCompletedEventHandler GetLinkMediaCompleted;
        
        /// <remarks/>
        public event GetLinkMediaByCateCompletedEventHandler GetLinkMediaByCateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLinkMedia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLinkMedia(string UserName, string Password, string MSISDN, int MediaType, string MediaID, int ChannelType, double Price, string RequestTime) {
            object[] results = this.Invoke("GetLinkMedia", new object[] {
                        UserName,
                        Password,
                        MSISDN,
                        MediaType,
                        MediaID,
                        ChannelType,
                        Price,
                        RequestTime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLinkMediaAsync(string UserName, string Password, string MSISDN, int MediaType, string MediaID, int ChannelType, double Price, string RequestTime) {
            this.GetLinkMediaAsync(UserName, Password, MSISDN, MediaType, MediaID, ChannelType, Price, RequestTime, null);
        }
        
        /// <remarks/>
        public void GetLinkMediaAsync(string UserName, string Password, string MSISDN, int MediaType, string MediaID, int ChannelType, double Price, string RequestTime, object userState) {
            if ((this.GetLinkMediaOperationCompleted == null)) {
                this.GetLinkMediaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLinkMediaOperationCompleted);
            }
            this.InvokeAsync("GetLinkMedia", new object[] {
                        UserName,
                        Password,
                        MSISDN,
                        MediaType,
                        MediaID,
                        ChannelType,
                        Price,
                        RequestTime}, this.GetLinkMediaOperationCompleted, userState);
        }
        
        private void OnGetLinkMediaOperationCompleted(object arg) {
            if ((this.GetLinkMediaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLinkMediaCompleted(this, new GetLinkMediaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLinkMediaByCate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLinkMediaByCate(string UserName, string Password, string MSISDN, int MediaType, int CateID, string MediaID, int ChannelType, double Price, string RequestTime) {
            object[] results = this.Invoke("GetLinkMediaByCate", new object[] {
                        UserName,
                        Password,
                        MSISDN,
                        MediaType,
                        CateID,
                        MediaID,
                        ChannelType,
                        Price,
                        RequestTime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLinkMediaByCateAsync(string UserName, string Password, string MSISDN, int MediaType, int CateID, string MediaID, int ChannelType, double Price, string RequestTime) {
            this.GetLinkMediaByCateAsync(UserName, Password, MSISDN, MediaType, CateID, MediaID, ChannelType, Price, RequestTime, null);
        }
        
        /// <remarks/>
        public void GetLinkMediaByCateAsync(string UserName, string Password, string MSISDN, int MediaType, int CateID, string MediaID, int ChannelType, double Price, string RequestTime, object userState) {
            if ((this.GetLinkMediaByCateOperationCompleted == null)) {
                this.GetLinkMediaByCateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLinkMediaByCateOperationCompleted);
            }
            this.InvokeAsync("GetLinkMediaByCate", new object[] {
                        UserName,
                        Password,
                        MSISDN,
                        MediaType,
                        CateID,
                        MediaID,
                        ChannelType,
                        Price,
                        RequestTime}, this.GetLinkMediaByCateOperationCompleted, userState);
        }
        
        private void OnGetLinkMediaByCateOperationCompleted(object arg) {
            if ((this.GetLinkMediaByCateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLinkMediaByCateCompleted(this, new GetLinkMediaByCateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetLinkMediaCompletedEventHandler(object sender, GetLinkMediaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLinkMediaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLinkMediaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetLinkMediaByCateCompletedEventHandler(object sender, GetLinkMediaByCateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLinkMediaByCateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLinkMediaByCateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591